#!/bin/bash


# Variaveis locais
ext="eno1"                # Interface de rede externa
int="enp2s0"              # Interface de rede interna
lnet="192.168.0.0/24"     # endereço da rede local
server="192.168.0.254"    # endereço do servidor


#==  Funcoes para definicao de regras ======================================================#


local(){
    # Funcao para configuracao das regras de firewall para comunicacao local

    # Permite trafego nas portas (80, 443, 53, 123)
        iptables -t filter -A INPUT -i $ext -p tcp -m multiport --sports 80,443 -j ACCEPT
        iptables -t filter -A INPUT -i $ext -p udp -m multiport --sports 53,123 -j ACCEPT
        iptables -t filter -A OUTPUT -o $ext -p tcp -m multiport --dports 80,443 -j ACCEPT
        iptables -t filter -A OUTPUT -o $ext -p udp -m multiport --dports 53,123 -j ACCEPT

    # Permitir portas do DNS e HTTP para o servidor realizar
        iptables -A INPUT -d $server -p tcp --sport 80 -j ACCEPT
        iptables -A INPUT -d $server -p tcp --sport 53 -j ACCEPT
        iptables -A INPUT -d $server -p udp --sport 53 -j ACCEPT

    # Libera o trafego DHCP na rede externa
        iptables -t filter -A INPUT -i $ext -p udp --dport 68 -j ACCEPT
        iptables -t filter -A OUTPUT -o $ext -p udp --sport 68 -j ACCEPT
        iptables -t filter -A INPUT -i $ext -p udp --dport 67 -j ACCEPT
        iptables -t filter -A OUTPUT -o $ext -p udp --sport 67 -j ACCEPT

    # Libera todo o trafego da lo
        iptables -t filter -A INPUT -i lo -j ACCEPT
        iptables -t filter -A OUTPUT -o lo -j ACCEPT

    # Permitir tráfego ICMP de entrada e saída necessários para o funcionamento normal
        iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 10/s -j ACCEPT
        iptables -A OUTPUT -p icmp --icmp-type echo-reply -m limit --limit 10/s -j ACCEPT

    # Descartar tráfego ICMP de entrada e saída além das regras permitidas acima
        iptables -A INPUT -p icmp -j DROP
        iptables -A OUTPUT -p icmp -j DROP

    # Libera o trafego TCP do Squid (3128)
        iptables -t filter -A INPUT -i $int -p tcp --dport 3128 -j ACCEPT
        iptables -t filter -A OUTPUT -o $int -p tcp --sport 3128 -j ACCEPT

    # libera a porta SSH (22)
        iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
        iptables -t filter -A OUTPUT -p tcp --sport 22 -j ACCEPT

    # Libera trafego nas portas do Samba (135, 137, 138, 139 e 445)
        sambaports="135,137,138,139,445"
        iptables -t filter -A INPUT -s $lnet -p tcp -m multiport --dports $sambaports -j ACCEPT
        iptables -t filter -A INPUT -s $lnet -p udp -m multiport --sports $sambaports -j ACCEPT
        iptables -t filter -A OUTPUT -s $lnet -p tcp -m multiport --sports $sambaports -j ACCEPT
        iptables -t filter -A OUTPUT -s $lnet -p udp -m multiport --sports $sambaports -j ACCEPT

    # Permite portas para o funcionamento do samba-ad-dc
        samba_ad_dc_tcp="53,88,135,139,389,445,464,636,1024:5000,49152:65535,3268,3269,5353"
        samba_ad_dc_udp="53,88,137,138,389,5353"
        iptables -A INPUT -s $lnet -p tcp -m multiport --dports $samba_ad_dc_tcp -j ACCEPT
        iptables -A INPUT -s $lnet -p udp -m multiport --dports $samba_ad_dc_udp -j ACCEPT

        iptables -t filter -A OUTPUT -p udp --sport 389 -j ACCEPT

    # Multicast e DNS (5353, 53)
        iptables -t filter -A INPUT -p tcp --dport 5353 -j ACCEPT
        iptables -t filter -A INPUT -p udp --dport 5353 -j ACCEPT

        iptables -A INPUT -i $ext -d 224.0.0.0/4 -j ACCEPT
        iptables -A OUTPUT -o $ext -d 224.0.0.0/4 -j ACCEPT

        iptables -A INPUT -i $int -p udp --dport 53 -j ACCEPT
        iptables -A OUTPUT -o $int -p udp --sport 53 -j ACCEPT

    #Libera o trafego DHCP (67, 68)
        iptables -t filter -A INPUT -i $int -p udp --dport 68 -j ACCEPT
        iptables -t filter -A OUTPUT -o $int -p udp --sport 68 -j ACCEPT
        iptables -t filter -A INPUT -i $int -p udp --dport 67 -j ACCEPT
        iptables -t filter -A OUTPUT -o $int -p udp --sport 67 -j ACCEPT

    # Libera o NTP (123)
        iptables -t filter -A INPUT -p udp --dport 123 -j ACCEPT

    # Regras para permitir conexões relacionadas e estabelecidas
        iptables -t filter -A INPUT -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT
        iptables -t filter -A OUTPUT -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT
}


forward(){
    # Funcao para encaminhamento de trafego entre WAN e LAN

    # Libera o trafego entre a INTERNET e a REDE LOCAL
        iptables -t filter -A FORWARD -i $ext -p tcp -m multiport --sports 80,443 -d $lnet -j ACCEPT
        iptables -t filter -A FORWARD -i $ext -p udp -m multiport --sports 53,123 -d $lnet -j ACCEPT
        iptables -t filter -A FORWARD -i $int -p tcp -m multiport --dports 80,443 -s $lnet -j ACCEPT
        iptables -t filter -A FORWARD -i $int -p udp -m multiport --dports 53,123 -s $lnet -j ACCEPT

    # Libera o ping entre a INTERNET e a REDE LOCAL
        iptables -t filter -A FORWARD -i $int -p icmp --icmp-type 8 -s $lnet -j ACCEPT
        iptables -t filter -A FORWARD -o $int -p icmp --icmp-type 0 -d $lnet -j ACCEPT
        iptables -t filter -A FORWARD -i $ext -p icmp --icmp-type 0 -d $lnet -j ACCEPT
        iptables -t filter -A FORWARD -o $ext -p icmp --icmp-type 8 -s $lnet -j ACCEPT

    # Permitir tráfego ICMP de encaminhamento necessários para o funcionamento normal
        iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 10/s -j ACCEPT
        iptables -A FORWARD -p icmp --icmp-type echo-reply -m limit --limit 10/s -j ACCEPT

    # Descartar tráfego ICMP de encaminhamento além das regras permitidas acima
        iptables -A FORWARD -p icmp -j DROP
}


internet(){
    # Funcao para habilitar o compartilhamento da internet entre as redes

    # Habilita o encaminhamento de IP
    sysctl -w net.ipv4.ip_forward=1

    # Configura NAT para o trafego da LAN para a Internet
    iptables -t nat -A POSTROUTING -s $lnet -o $ext -j MASQUERADE

    # Direcionar navegacao na porta HTTP (80) para a porta do proxy/squid (3128)
    iptables -t nat -A PREROUTING -i $int -p tcp --dport 80 -j REDIRECT --to-port 3128
}


#==  Funcoes de controle  ==================================================================#

default() {
    iptables -N LOGGING
    iptables -A LOGGING -m limit --limit 5/min -j LOG --log-prefix "iptables-denied: " --log-level 7
    iptables -A LOGGING -j DROP

    iptables -t filter -A INPUT -j LOGGING
    iptables -t filter -A OUTPUT -j LOGGING
    iptables -t filter -A FORWARD -j LOGGING

    iptables -P INPUT DROP
    iptables -P OUTPUT DROP
    iptables -P FORWARD DROP
}

iniciar(){
    # Funcao para iniciar o firewall
    local
    forward
    internet
    default
}


parar(){
    # Funcao para parar o firewall
    iptables -t filter -P INPUT ACCEPT
    iptables -t filter -P OUTPUT ACCEPT
    iptables -t filter -P FORWARD ACCEPT
    iptables -t filter -F
    iptables -F
    iptables -X
}


#==  Script para controle do firewall  =====================================================#


case $1 in
    start|Start|START)iniciar;;
    stop|Stop|STOP)parar;;
    restart|Restart|RESTART)parar;iniciar;;
    listar|list)iptables -t filter -nvL;;
    vi|conf)sudo vi /usr/local/sbin/firewall;;
    *)echo "usage:
    firewall [start|stop|restart|list|vi]";;
esac